
# DATASOURCE
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER}/${DB_USERNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
